### PR TITLE
Clicksend upgrade v5

### PR DESCRIPTION
**Pull request by dragonfly4**
Clicksend requirement changed to version 5

### CODE REVIEW

**Comment by parkourben99** [comment]
@dragonfly4 is there any changes to the api for this version change?

**Comment by dragonfly4** [comment]
@parkourben99 I don't think so. Happy to test it for you unless you have a running test environment?

https://github.com/ClickSend/clicksend-php/compare/v4.0.4...master

**Comment by parkourben99** [comment]
> @parkourben99 I don't think so. Happy to test it for you unless you have a running test environment?
> 
> [ClickSend/clicksend-php@v4.0.4...master](https://github.com/ClickSend/clicksend-php/compare/v4.0.4...master)

If you could please

**Comment by dragonfly4** [comment]
There are breaking changes so the package will need to be updated to use with v5.

https://developers.clicksend.com/docs/rest/v3/#ClickSend-v3-API-SMS

**Pull request closed without merging**
